platform :ios, '9.0'
target 'GalleryImageUpload' do
  use_frameworks!
  inhibit_all_warnings!
  # Pods for GalleryImageUpload

    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'AlamofireImage'

  target 'GalleryImageUploadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GalleryImageUploadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
